doctrine:
    dbal:
        connections:
            default:
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                dbname: '%env(resolve:DATABASE_SCHEMA)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
            idp:
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                dbname: '%env(resolve:IDP_DATABASE_SCHEMA)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
            finance:
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                dbname: '%env(resolve:BANKING_DATABASE_SCHEMA)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
        types:
            carbon_immutable: \Carbon\Doctrine\CarbonImmutableType
            carbon: \Carbon\Doctrine\CarbonType

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    AppEntities:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        type: attribute
            idp:
                connection: idp
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    IdpEntities:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/External/User'
                        prefix: 'App\External'
                        alias: Idp
                        type: attribute
            finance:
                connection: finance
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    financeEntities:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/External/Finance'
                        prefix: 'App\External'
                        alias: Finance
                        type: attribute

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'
                idp:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system






















#doctrine:
#    dbal:
#        host: '%env(resolve:DATABASE_HOST)%'
#        port: '%env(resolve:DATABASE_PORT)%'
#        dbname: '%env(resolve:DATABASE_SCHEMA)%'
#        user: '%env(resolve:DATABASE_USER)%'
#        password: '%env(resolve:DATABASE_PASSWORD)%'
#        driver: 'pdo_mysql'
#        server_version: '8.0'
#        charset: utf8mb4
#        profiling_collect_backtrace: '%kernel.debug%'
#        use_savepoints: true
#        types:
#            carbon_immutable: \Carbon\Doctrine\CarbonImmutableType
#            carbon: \Carbon\Doctrine\CarbonType
#    orm:
#        enable_native_lazy_objects: true
#        auto_generate_proxy_classes: true
#        enable_lazy_ghost_objects: true
#        report_fields_where_declared: true
#        validate_xml_mapping: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        identity_generation_preferences:
#            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
#        auto_mapping: true
#        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
#        controller_resolver:
#            auto_mapping: false
#
#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
#
#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool
#
#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
